In [1]:
import pandas as pd
from yahooquery import Ticker
import time
import yfinance as yf

In [14]:
import plotly.express as px
import plotly.io as pio

In [2]:
df = pd.read_csv('data/19_CG001_Holdings_clean.csv')
# df = pd.read_csv('data/R2500G_proxy_Holdings_clean.csv')
df

,Security Name,Ticker,Shares,Price [USD],Market Value [USD],Weight (%),Industry,Sector
0,Addus HomeCare Corporation,ADUS,6377,102.86,655938.22,2.0173,Medical Care Facilities,Healthcare
1,"ADMA Biologics, Inc.",ADMA,41712,24.11,1005676.32,3.0928,Biotechnology,Healthcare
2,Artisan Partners Asset Management Inc.,APAM,16320,37.56,612979.20,1.8851,Asset Management,Financial Services
3,Avery Dennison Corporation,AVY,2050,171.72,352026.00,1.0826,Packaging & Containers,Consumer Cyclical
4,Bruker Corporation,BRKR,5404,39.84,215295.36,0.6621,Medical Devices,Healthcare
5,"BWX Technologies, Inc.",BWXT,7836,109.24,856004.64,2.6325,Aerospace & Defense,Industrials
6,"Commvault Systems, Inc.",CVLT,5064,168.73,854448.72,2.6278,Software - Application,Technology
7,Corcept Therapeutics Incorporated,CORT,3914,73.23,286622.22,0.8815,Biotechnology,Healthcare
8,"DICK'S Sporting Goods, Inc.",DKS,3471,192.01,666466.71,2.0496,Specialty Retail,Consumer Cyclical
9,"e.l.f. Beauty, Inc.",ELF,2904,62.17,180541.68,0.5552,Household & Personal Products,Consumer Defensive
10,"EMCOR Group, Inc.",EME,1217,413.02,502645.34,1.5458,Engineering & Construction,Industrials
11,"Exelixis, Inc.",EXEL,16511,38.55,636499.05,1.9575,Biotechnology,Healthcare
12,"ExlService Holdings, Inc.",EXLS,21285,44.98,957399.30,2.9444,Information Technology Services,Technology
13,Fabrinet,FN,4996,207.55,1036919.80,3.1889,Electronic Components,Technology
14,FactSet Research Systems Inc.,FDS,1169,428.71,501161.99,1.5413,Financial Data & Stock Exchanges,Financial Services
15,"Halozyme Therapeutics, Inc.",HALO,3614,60.82,219803.48,0.6760,Biotechnology,Healthcare
16,"Inspire Medical Systems, Inc.",INSP,5183,159.93,828917.19,2.5492,Medical Devices,Healthcare
17,"InterDigital, Inc.",IDCC,5863,200.53,1175707.39,3.6158,Software - Application,Technology
18,IRADIMED CORPORATION,IRMD,10602,53.70,569327.40,1.7509,Medical Devices,Healthcare
19,"Ironwood Pharmaceuticals, Inc.",IRWD,26147,0.94,24583.41,0.0756,Drug Manufacturers - Specialty & Generic,Healthcare
20,"KBR, Inc.",KBR,11779,52.88,622873.52,1.9156,Engineering & Construction,Industrials
21,Lamar Advertising Company,LAMR,8742,114.53,1001221.26,3.0791,REIT - Specialty,Real Estate
22,"Lantheus Holdings, Inc.",LNTH,12173,103.96,1265505.08,3.8919,Semiconductor Equipment & Materials,Technology
23,"Light & Wonder, Inc.",LNW,6880,85.08,585350.40,1.8002,Drug Manufacturers - Specialty & Generic,Healthcare
24,"Napco Security Technologies, Inc.",NSSC,9258,22.87,211730.46,0.6512,Drug Manufacturers - Specialty & Generic,Healthcare
25,"Neurocrine Biosciences, Inc.",NBIX,6466,107.24,693413.84,2.1325,Security & Protection Services,Industrials
26,Nextracker Inc.,NXT,4877,43.07,210052.39,0.6460,Medical Care Facilities,Healthcare
27,Onto Innovation Inc.,ONTO,7305,122.28,893255.40,2.7471,Solar,Technology
28,"Option Care Health, Inc.",OPCH,6389,30.69,196078.41,0.6030,Electronic Components,Technology
29,"OSI Systems, Inc.",OSIS,5864,203.12,1191095.68,3.6631,Recreational Vehicles,Consumer Cyclical
30,"Patrick Industries, Inc.",PATK,10669,78.52,837729.88,2.5763,Software - Application,Technology
31,Paylocity Holding Corporation,PCTY,2251,192.33,432934.83,1.3314,Software - Infrastructure,Technology
32,"Qualys, Inc.",QLYS,5540,128.43,711502.20,2.1881,Trucking,Industrials
33,"Saia, Inc.",SAIA,2905,236.65,687468.25,2.1142,Software - Application,Technology
34,"Sprouts Farmers Market, Inc.",SFM,8827,172.30,1520892.10,4.6773,Banks - Regional,Financial Services
35,"SPS Commerce, Inc.",SPSC,3050,142.00,433100.00,1.3320,Engineering & Construction,Industrials
36,"Sterling Infrastructure, Inc.",STRL,1028,149.28,153459.84,0.4719,Specialty Industrial Machinery,Industrials
37,Tennant Company,TNC,13453,72.89,980589.17,3.0157,Engineering & Construction,Industrials
38,"Tetra Tech, Inc.",TTEK,26996,31.27,844164.92,2.5961,Grocery Stores,Consumer Defensive
39,"The Bancorp, Inc.",TBBK,29263,48.75,1426571.25,4.3873,Electronic Components,Technology

In [3]:
tickers = df["Ticker"].tolist()

return_history = "1y"
return_interval = "1d"

data = yf.download(tickers, period=return_history,
                              interval=return_interval,
                              progress=True, auto_adjust=True)


portfolio = data['Close'].copy()

[*********************100%***********************]  40 of 40 completed

In [12]:
ret = (portfolio.iloc[-1]/portfolio.iloc[0]) - 1
df['Return (%)'] = ret.fillna(0).tolist()

In [13]:
df

,Security Name,Ticker,Shares,Price [USD],Market Value [USD],Weight (%),Industry,Sector,Return (%)
0,Addus HomeCare Corporation,ADUS,6377,102.86,655938.22,2.0173,Medical Care Facilities,Healthcare,-0.527506
1,"ADMA Biologics, Inc.",ADMA,41712,24.11,1005676.32,3.0928,Biotechnology,Healthcare,-0.096122
2,Artisan Partners Asset Management Inc.,APAM,16320,37.56,612979.20,1.8851,Asset Management,Financial Services,0.079338
3,Avery Dennison Corporation,AVY,2050,171.72,352026.00,1.0826,Packaging & Containers,Consumer Cyclical,-0.006753
4,Bruker Corporation,BRKR,5404,39.84,215295.36,0.6621,Medical Devices,Healthcare,-0.018638
5,"BWX Technologies, Inc.",BWXT,7836,109.24,856004.64,2.6325,Aerospace & Defense,Industrials,1.267736
6,"Commvault Systems, Inc.",CVLT,5064,168.73,854448.72,2.6278,Software - Application,Technology,-0.464659
7,Corcept Therapeutics Incorporated,CORT,3914,73.23,286622.22,0.8815,Biotechnology,Healthcare,-0.477206
8,"DICK'S Sporting Goods, Inc.",DKS,3471,192.01,666466.71,2.0496,Specialty Retail,Consumer Cyclical,0.061836
9,"e.l.f. Beauty, Inc.",ELF,2904,62.17,180541.68,0.5552,Household & Personal Products,Consumer Defensive,0.111596
10,"EMCOR Group, Inc.",EME,1217,413.02,502645.34,1.5458,Engineering & Construction,Industrials,1.137608
11,"Exelixis, Inc.",EXEL,16511,38.55,636499.05,1.9575,Biotechnology,Healthcare,0.196292
12,"ExlService Holdings, Inc.",EXLS,21285,44.98,957399.30,2.9444,Information Technology Services,Technology,-0.328559
13,Fabrinet,FN,4996,207.55,1036919.80,3.1889,Electronic Components,Technology,-0.471609
14,FactSet Research Systems Inc.,FDS,1169,428.71,501161.99,1.5413,Financial Data & Stock Exchanges,Financial Services,2.233484
15,"Halozyme Therapeutics, Inc.",HALO,3614,60.82,219803.48,0.6760,Biotechnology,Healthcare,0.041505
16,"Inspire Medical Systems, Inc.",INSP,5183,159.93,828917.19,2.5492,Medical Devices,Healthcare,0.595934
17,"InterDigital, Inc.",IDCC,5863,200.53,1175707.39,3.6158,Software - Application,Technology,-0.631952
18,IRADIMED CORPORATION,IRMD,10602,53.70,569327.40,1.7509,Medical Devices,Healthcare,0.901347
19,"Ironwood Pharmaceuticals, Inc.",IRWD,26147,0.94,24583.41,0.0756,Drug Manufacturers - Specialty & Generic,Healthcare,1.602941
20,"KBR, Inc.",KBR,11779,52.88,622873.52,1.9156,Engineering & Construction,Industrials,-0.247285
21,Lamar Advertising Company,LAMR,8742,114.53,1001221.26,3.0791,REIT - Specialty,Real Estate,0.228154
22,"Lantheus Holdings, Inc.",LNTH,12173,103.96,1265505.08,3.8919,Semiconductor Equipment & Materials,Technology,-0.217159
23,"Light & Wonder, Inc.",LNW,6880,85.08,585350.40,1.8002,Drug Manufacturers - Specialty & Generic,Healthcare,0.000000
24,"Napco Security Technologies, Inc.",NSSC,9258,22.87,211730.46,0.6512,Drug Manufacturers - Specialty & Generic,Healthcare,0.279160
25,"Neurocrine Biosciences, Inc.",NBIX,6466,107.24,693413.84,2.1325,Security & Protection Services,Industrials,0.912793
26,Nextracker Inc.,NXT,4877,43.07,210052.39,0.6460,Medical Care Facilities,Healthcare,1.799010
27,Onto Innovation Inc.,ONTO,7305,122.28,893255.40,2.7471,Solar,Technology,0.962396
28,"Option Care Health, Inc.",OPCH,6389,30.69,196078.41,0.6030,Electronic Components,Technology,-0.213795
29,"OSI Systems, Inc.",OSIS,5864,203.12,1191095.68,3.6631,Recreational Vehicles,Consumer Cyclical,0.486939
30,"Patrick Industries, Inc.",PATK,10669,78.52,837729.88,2.5763,Software - Application,Technology,0.452703
31,Paylocity Holding Corporation,PCTY,2251,192.33,432934.83,1.3314,Software - Infrastructure,Technology,-0.419238
32,"Qualys, Inc.",QLYS,5540,128.43,711502.20,2.1881,Trucking,Industrials,-0.283199
33,"Saia, Inc.",SAIA,2905,236.65,687468.25,2.1142,Software - Application,Technology,0.107229
34,"Sprouts Farmers Market, Inc.",SFM,8827,172.30,1520892.10,4.6773,Banks - Regional,Financial Services,-0.494128
35,"SPS Commerce, Inc.",SPSC,3050,142.00,433100.00,1.3320,Engineering & Construction,Industrials,-0.567384
36,"Sterling Infrastructure, Inc.",STRL,1028,149.28,153459.84,0.4719,Specialty Industrial Machinery,Industrials,2.786286
37,Tennant Company,TNC,13453,72.89,980589.17,3.0157,Engineering & Construction,Industrials,0.136642
38,"Tetra Tech, Inc.",TTEK,26996,31.27,844164.92,2.5961,Grocery Stores,Consumer Defensive,-0.060238
39,"The Bancorp, Inc.",TBBK,29263,48.75,1426571.25,4.3873,Electronic Components,Technology,0.042732

# optimization

In [6]:
start = time.perf_counter()
symbols = df['Ticker'].tolist()

start_date = "2025-06-01"
end_date = "2025-08-01"

tickers = Ticker(symbols, asynchronous=True)
df_1 = tickers.history(
    start=start_date,
    end=end_date,
    interval="1d"
)

elapsed = time.perf_counter() - start
print(f"Elapsed: {elapsed:.3f} s")

Elapsed: 43.402 s

In [7]:
return_history = "1y"
return_interval = "1d"


start = time.perf_counter()
data = yf.download(symbols, period=return_history,
                              interval=return_interval,
                              progress=False, auto_adjust=True)

elapsed = time.perf_counter() - start
print(f"Elapsed: {elapsed:.3f} s")

$LBPH: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$BPMC: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$SQSP: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$LLAP: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$PWSC: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$RDFN: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$UHAL.B: possibly delisted; no price data found  (period=1y)
$GMS: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$CRD.A: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$PSTX: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$INST: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$AXNX: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$SILK: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$ENV: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$PETQ: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$SKX: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$ATRI: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$MRSN: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$JAMF: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$GTHX: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$ITI: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$PRMW: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$COOP: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$REVG: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$SMAR: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$RVNC: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$MOG.A: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$AMK: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$ALIM: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$SCPH: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$CDMO: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")

31 Failed downloads:
['LBPH', 'BPMC', 'SQSP', 'LLAP', 'PWSC', 'RDFN', 'GMS', 'CRD.A', 'PSTX', 'INST', 'AXNX', 'SILK', 'ENV', 'PETQ', 'SKX', 'ATRI', 'MRSN', 'JAMF', 'GTHX', 'ITI', 'PRMW', 'COOP', 'REVG', 'SMAR', 'RVNC', 'MOG.A', 'AMK', 'ALIM', 'SCPH', 'CDMO']: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
['UHAL.B']: possibly delisted; no price data found  (period=1y)

Elapsed: 64.931 s

In [8]:
start = time.perf_counter()
data = yf.download(symbols, period=return_history,
                              interval=return_interval,
                              progress=True, auto_adjust=True)

elapsed = time.perf_counter() - start
print(f"Elapsed: {elapsed:.3f} s")

[****                   8%                       ]  88 of 1123 completed$LBPH: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[******                13%                       ]  141 of 1123 completed$BPMC: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[***********           22%                       ]  242 of 1123 completed$PWSC: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[***********           22%                       ]  243 of 1123 completed$SQSP: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[***********           23%                       ]  259 of 1123 completed$LLAP: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**************        29%                       ]  328 of 1123 completed$RDFN: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[***************       31%                       ]  348 of 1123 completed$UHAL.B: possibly delisted; no price data found  (period=1y)
[*******************   39%                       ]  441 of 1123 completed$CRD.A: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[*******************   39%                       ]  442 of 1123 completed$PSTX: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[********************  42%                       ]  469 of 1123 completed$INST: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[********************  42%                       ]  471 of 1123 completed$GMS: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[********************* 43%                       ]  487 of 1123 completed$AXNX: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************48%                       ]  535 of 1123 completed$ENV: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************48%                       ]  536 of 1123 completed$SILK: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************49%                       ]  551 of 1123 completed$PETQ: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************49%                       ]  552 of 1123 completed$SKX: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************51%                       ]  570 of 1123 completed$ATRI: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************55%*                      ]  615 of 1123 completed$MRSN: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************61%****                   ]  683 of 1123 completed$JAMF: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************68%********               ]  766 of 1123 completed$GTHX: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************74%***********            ]  829 of 1123 completed$ITI: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$PRMW: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************81%**************         ]  911 of 1123 completed$COOP: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************84%***************        ]  942 of 1123 completed$REVG: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************85%****************       ]  958 of 1123 completed$SMAR: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************92%*******************    ]  1030 of 1123 completed$RVNC: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************92%*******************    ]  1031 of 1123 completed$MOG.A: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************96%*********************  ]  1083 of 1123 completed$AMK: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************97%********************** ]  1084 of 1123 completed$ALIM: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************99%***********************]  1107 of 1123 completed$SCPH: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************99%***********************]  1108 of 1123 completed$CDMO: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[*********************100%***********************]  1123 of 1123 completed

31 Failed downloads:
['LBPH', 'BPMC', 'PWSC', 'SQSP', 'LLAP', 'RDFN', 'CRD.A', 'PSTX', 'INST', 'GMS', 'AXNX', 'ENV', 'SILK', 'PETQ', 'SKX', 'ATRI', 'MRSN', 'JAMF', 'GTHX', 'ITI', 'PRMW', 'COOP', 'REVG', 'SMAR', 'RVNC', 'MOG.A', 'AMK', 'ALIM', 'SCPH', 'CDMO']: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
['UHAL.B']: possibly delisted; no price data found  (period=1y)

Elapsed: 61.051 s

# download data

In [1]:
import pandas as pd
import yfinance as yf

In [2]:
df = pd.read_csv("data/19_CG001_Holdings_clean.csv")

tickers = df["Ticker"].tolist()

return_history = "1y"
return_interval = "1d"

data = yf.download(tickers, period=return_history,
                              interval=return_interval,
                              progress=True, auto_adjust=True)

[*********************100%***********************]  39 of 39 completed

In [ ]:
# data.to_csv('data/data.csv')

In [14]:
pp = pd.read_csv('data/etf_factor_data.csv')
pp

           MTUM        QUAL        SIZE        VLUE
0    193.431641  162.999725  137.802094   99.617134
1    179.712158  153.968964  130.005341   93.721069
2    181.249786  153.077743  128.420380   93.369064
3    179.394730  150.928986  126.156174   91.423271
4    198.193268  164.029556  138.018692   98.551346
..          ...         ...         ...         ...
246  235.759995  187.300003  156.029999  141.080002
247  230.770004  186.490005  155.440002  138.479996
248  239.990005  191.809998  159.460007  142.190002
249  245.240005  192.770004  159.809998  144.759995
250  245.850006  193.160004  160.410004  145.220001

[251 rows x 4 columns]

In [16]:
mmm = pd.read_csv('data/market_data.csv')
mmm.pct_change()

       CSUS.L
0         NaN
1   -0.037530
2   -0.050562
3   -0.033627
4    0.036537
..        ...
246 -0.013191
247 -0.017229
248 -0.000907
249  0.005748
250  0.021206

[251 rows x 1 columns]

In [4]:
portfolio = data['Close'].copy()
portfolio

Ticker,ADMA,ADUS,APAM,AVY,BRKR,BWXT,CORT,CVLT,DKS,ELF,...,PATK,PCTY,QLYS,SAIA,SFM,SPSC,STRL,TBBK,TNC,TTEK
Date,,,,,,,,,,,,,,,,,,,,,
2025-04-03,19.450001,101.330002,33.881878,172.635834,37.458130,94.799408,79.370003,152.889999,180.583496,55.020000,...,78.846130,182.759995,123.269997,319.970001,153.279999,129.630005,109.959999,48.959999,74.316681,29.796738
2025-04-04,18.010000,100.309998,32.380085,166.673767,36.264561,88.659592,74.449997,139.350006,178.533295,54.930000,...,77.359947,174.880005,118.589996,322.380005,145.289993,127.900002,104.959999,43.919998,73.244766,28.893208
2025-04-07,18.400000,97.000000,31.766544,162.787155,38.492558,89.434525,74.650002,142.080002,173.056320,53.880001,...,76.336357,174.809998,116.989998,325.309998,147.289993,123.279999,109.099998,40.930000,70.186348,28.009531
2025-04-08,17.860001,96.320000,30.997337,156.227905,36.165104,92.564034,70.489998,140.509995,167.140045,51.000000,...,73.157318,172.539993,115.209999,323.070007,144.630005,121.610001,113.830002,42.029999,68.376854,27.810951
2025-04-09,19.389999,101.000000,34.010075,165.312973,40.969208,103.403091,72.970001,157.720001,193.245926,55.740002,...,80.263412,187.740005,125.730003,374.799988,153.660004,135.839996,134.529999,46.990002,72.389191,29.657734
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-27,9.250000,95.190002,35.130001,167.779999,33.720001,202.589996,37.599998,76.080002,189.360001,61.049999,...,107.389999,105.389999,85.629997,334.309998,77.400002,54.490002,420.239990,51.480000,66.500000,29.780001
2026-03-30,9.150000,94.379997,35.599998,168.149994,34.310001,191.589996,38.119999,75.180000,190.619995,59.349998,...,105.699997,108.629997,87.919998,336.010010,77.260002,55.080002,382.549988,51.910000,64.330002,29.760000
2026-03-31,9.010000,93.650002,36.389999,172.679993,36.119999,204.490005,40.310001,77.889999,198.289993,60.610001,...,111.070000,108.040001,87.849998,351.279999,77.129997,55.669998,407.269989,53.730000,66.400002,30.120001
2026-04-01,9.110000,93.849998,36.560001,173.100006,36.080002,212.809998,41.980000,78.410004,192.130005,62.299999,...,112.989998,105.180000,86.209999,354.880005,75.860001,56.230000,421.290009,54.810001,69.080002,30.730000
2026-04-02,9.190000,91.589996,36.570000,171.470001,36.759998,214.979996,42.490002,79.930000,191.750000,61.160000,...,114.540001,106.139999,88.360001,354.279999,77.540001,56.080002,416.339996,55.650002,69.839996,31.070000

In [ ]:
# portfolio.to_csv('data/portfolio.csv')

In [5]:
factor_tickers = ["SIZE", "VLUE", "MTUM", "QUAL"]
market_ticker = "CSUS.L"

etf_factor_data = yf.download(
    factor_tickers,
    period=return_history,
    interval=return_interval,
    progress=True,
    auto_adjust=True
)

market_data = yf.download(
    [market_ticker],
    period=return_history,
    interval=return_interval,
    progress=True,
    auto_adjust=True
)

[*********************100%***********************]  4 of 4 completed
[*********************100%***********************]  1 of 1 completed

In [ ]:
# etf_factor_data.to_csv('data/etf_factor_data.csv')
# market_data.to_csv('data/market_data.csv')

In [29]:
r2500 = pd.read_csv('data/R2500G_proxy_Holdings_clean.csv')
r2500

,Security Name,Ticker,Shares,Price [USD],Market Value [USD],Weight (%),industry,sector
0,"10x Genomics, Inc.",TXG,69.59,13.96,971.45,0.0477,Health Information Services,Healthcare
1,"1-800-FLOWERS.COM, Inc.",FLWS,6.24,5.10,31.84,0.0016,Specialty Retail,Consumer Cyclical
2,"1stdibs.Com, Inc.",DIBS,5.57,2.77,15.42,0.0008,Internet Content & Information,Communication Services
3,374Water Inc.,SCWO,64.72,0.39,25.49,0.0013,Pollution & Treatment Controls,Industrials
4,"4D Molecular Therapeutics, Inc.",FDMT,31.98,7.27,232.50,0.0114,Biotechnology,Healthcare
...,...,...,...,...,...,...,...,...
1118,VSE Corporation,VSEC,2.16,166.24,359.74,0.0177,Software - Infrastructure,Technology
1119,"W&T Offshore, Inc.",WTI,97.69,1.76,171.93,0.0084,Internet Content & Information,Communication Services
1120,"Walker & Dunlop, Inc.",WD,23.11,87.60,2024.44,0.0994,Software - Infrastructure,Technology
1121,Warby Parker Inc.,WRBY,86.36,26.02,2247.17,0.1103,Biotechnology,Healthcare
1122,WD-40 Company,WDFC,13.49,218.08,2942.34,0.1444,Pollution & Treatment Controls,Industrials

In [30]:
portfolio_data_loc = "data/R2500G_proxy_Holdings_clean.csv"
output_path = "data/all_close_prices.csv"

df_holdings = pd.read_csv(portfolio_data_loc)
all_tickers = (
    df_holdings["Ticker"]
    .dropna()
    .astype(str)
    .unique()
    .tolist()
)

price_data = yf.download(
    all_tickers,
    period="1y",
    interval="1d",
    progress=True,
    auto_adjust=True
)

close_df = price_data["Close"]

if isinstance(close_df, pd.Series):
    close_df = close_df.to_frame(name=all_tickers[0])

close_df = close_df.sort_index().ffill()

# 存檔
close_df.to_csv(output_path)

[                       1%                       ]  16 of 1123 completed$SKX: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[***                    6%                       ]  64 of 1123 completed$ENV: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[***                    7%                       ]  80 of 1123 completed$MOG.A: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[***                    7%                       ]  81 of 1123 completed$GMS: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[****                   9%                       ]  97 of 1123 completed$GTHX: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[*******               14%                       ]  152 of 1123 completed$SMAR: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[*******               15%                       ]  167 of 1123 completed$AXNX: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$AMK: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[*********             18%                       ]  201 of 1123 completed$COOP: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********            21%                       ]  232 of 1123 completed$RVNC: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********            21%                       ]  233 of 1123 completed$SCPH: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[****************      34%                       ]  383 of 1123 completed$ALIM: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$BPMC: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[*******************   40%                       ]  452 of 1123 completed$MRSN: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************48%                       ]  544 of 1123 completed$ITI: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************49%                       ]  545 of 1123 completed$PSTX: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************53%                       ]  590 of 1123 completed$PRMW: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************61%****                   ]  688 of 1123 completed$LBPH: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************63%*****                  ]  704 of 1123 completed$RDFN: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************66%*******                ]  740 of 1123 completed$SILK: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************69%********               ]  771 of 1123 completed$LLAP: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************69%********               ]  772 of 1123 completed$CDMO: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************73%**********             ]  817 of 1123 completed$UHAL.B: possibly delisted; no price data found  (period=1y)
[**********************76%***********            ]  858 of 1123 completed$PETQ: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************76%***********            ]  859 of 1123 completed$ATRI: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************78%************           ]  873 of 1123 completed$REVG: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************90%******************     ]  1006 of 1123 completed$INST: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************90%******************     ]  1007 of 1123 completed$CRD.A: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************91%*******************    ]  1022 of 1123 completed$SQSP: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************94%********************   ]  1056 of 1123 completed$JAMF: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[**********************94%********************   ]  1057 of 1123 completed$PWSC: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
[*********************100%***********************]  1123 of 1123 completed

31 Failed downloads:
['SKX', 'ENV', 'MOG.A', 'GMS', 'GTHX', 'SMAR', 'AXNX', 'AMK', 'COOP', 'RVNC', 'SCPH', 'ALIM', 'BPMC', 'MRSN', 'ITI', 'PSTX', 'PRMW', 'LBPH', 'RDFN', 'SILK', 'LLAP', 'CDMO', 'PETQ', 'ATRI', 'REVG', 'INST', 'CRD.A', 'SQSP', 'JAMF', 'PWSC']: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
['UHAL.B']: possibly delisted; no price data found  (period=1y)

In [43]:
all = pd.read_csv('data/all_close_prices.csv')
all.columns.unique

<bound method Index.unique of Index(['AAL', 'AAMI', 'AAON', 'ABSI', 'ABUS', 'ACAD', 'ACEL', 'ACHR', 'ACHV',
       'ACIC',
       ...
       'WGS', 'WHD', 'WLY', 'WMS', 'WRBY', 'WTI', 'WU', 'WULF', 'YORW', 'YOU'],
      dtype='str', length=1123)>

In [41]:
allclose = all.dropna(axis=1, how='all')
all.columns.unique

<bound method Index.unique of Index(['AAL', 'AAMI', 'AAON', 'ABSI', 'ABUS', 'ACAD', 'ACEL', 'ACHR', 'ACHV',
       'ACIC',
       ...
       'WGS', 'WHD', 'WLY', 'WMS', 'WRBY', 'WTI', 'WU', 'WULF', 'YORW', 'YOU'],
      dtype='str', length=1123)>

In [44]:
missing_tickers = all.columns[all.isna().all()].tolist()
print(missing_tickers)

['ALIM', 'AMK', 'ATRI', 'AXNX', 'BPMC', 'CDMO', 'COOP', 'CRD.A', 'ENV', 'GMS', 'GTHX', 'INST', 'ITI', 'JAMF', 'LBPH', 'LLAP', 'MOG.A', 'MRSN', 'PETQ', 'PRMW', 'PSTX', 'PWSC', 'RDFN', 'REVG', 'RVNC', 'SCPH', 'SILK', 'SKX', 'SMAR', 'SQSP', 'UHAL.B']

In [47]:
allclose = all.drop(columns=missing_tickers)

In [51]:
allclose.to_csv('data/all_close_prices.csv')

In [1]:
import pandas as pd

In [2]:
chh = pd.read_csv('data/R2500G_proxy_Holdings_clean.csv')

In [7]:
chh.groupby('sector').size()

sector
Basic Materials            39
Communication Services     42
Consumer Cyclical         135
Consumer Defensive         47
Energy                     40
Financial Services         98
Healthcare                304
Industrials               174
Real Estate                33
Technology                199
Utilities                  12
dtype: int64